### PR TITLE
Provide a function to sort without Query

### PR DESCRIPTION
**Pull request by christophehurpeau**
Thanks for this lib !

This adds the ability to call the sort operator without creating a query:

```
const mingo = require('mingo')
const sortedCollection = mingo.sort(collection, {student_id: 1, score: -1})
```

### CODE REVIEW

**Comment by christophehurpeau** [comment]
I don't know if it's a good argument, but if you do that tree shaking won't be possible anymore. Today, if my app only uses sort, the filtering functions could all be tree shaked and considerably reduce the size of this lib (I haven't check that yet, however).
I currently use filtering in the node part and sorting in the browser part, to resort the collection after receiving updates from the server.

**Comment by kofrasa** [comment]
I think you have a point about tree shaking. The library is growing and not everyone needs every bit of it. Without distinct modules, tree shaking may be one of few ways to retain only used functionality. 

I am not sure if it is a good idea to make an exception for the sort function from the rest of the aggregation functions and still exploring alternatives that can be generalised without increasing the api surface of the mingo object. My initial chaining idea is not good enough and can be provided in another library if wanted.

**Comment by stalniy** [comment]
@kofrasa in this case you can do something like this:

```js
import { Lazy } from 'mingo'
import { match, sort, unwind } from 'mingo/aggregation'

Lazy(collection).transform(
  match({ name:"John" }),
  sort({ student_id: 1, score: -1}),
  unwind({ path: "$sizes" })
)
```

The return vaue of `match`, `sort`, etc should be defined based on implementation details (e.g., it can be functions)

**Comment by kofrasa** [comment]
Yes, I think this is much cleaner that what has been proposed so far. I think once we are through with #90 it will be clear how to generalise the code to fit this in

I no longer merge PR created from branch `master` so this will have to be reworked and rebased to `development`

**Comment by stalniy** [comment]
By the way, currently this library does not support tree shaking because there is the single `export` statement in [ES6 version](https://github.com/kofrasa/mingo/blob/master/dist/mingo.es6.js#L4339). So, this can't be statically analyzed by webpack or rollup.

**Comment by kofrasa** [comment]
You can import the sort operator directly to use use for your collection starting from `3.0.0`

**Comment by christophehurpeau** [comment]
For reference, this is the sort function with the v3 api:

```
import { Lazy } from 'mingo/lazy';
import { $sort } from 'mingo/operators/pipeline';

function sortCollection(collection, sort) {
  return $sort(Lazy(collection), sort, { config: { idKey: '_id' } }).value();
}
```

**Comment by kofrasa** [comment]
Thanks for adding the example. 

In the next update, I will wrap the input collection with the function itself to save the extra manual work.

**Pull request closed without merging**
