### PR TITLE
fix: Implement statistical $round for even or odd numbers for smaller decimal offsets

### LINKED ISSUE #304: Strange behaviour in $round
Hi, Thanks for the awesome project!

Found strange behaviour for `$round`. Please see the following:
```js
let agg = new Aggregator([
  { $project: { 
        A: {$round: [ '$value', 3]},
        B: '$value'
  } }
]);
let result = agg.run([{ value: 1.6016 }]);
// result is: [{ A: 1.601, B: 1.602 }]
```
I know, that Mongo implements a better statistical rounding algorithm, (https://www.mongodb.com/docs/manual/reference/operator/aggregation/round/#rounding-to-even-values), but in the case of ...16 I'd expect it to round to ...2 not ...1. Is this intentional for some reason?

Thanks again.

### PR DESCRIPTION
**Pull request by Gervwyk**
closes #304

### CODE REVIEW

**Comment by Gervwyk** [comment]
Sorry, see that you already implemented a fix in the meantime. Thanks!
I'll leave this one here for you to have a look.

**Comment by Gervwyk** [comment]
I've added test cases as verified on mongodb. Two test cases are still failing:
```
      ✕ can apply $round([0.0115,3]) => 0.012 (1 ms)
      ✕ can apply $round([0.0125,3]) => 0.013
```
Will attempt a fix a little later. 
I did an alternative bit overflow fix. 
```js
const decimals = parseFloat((num - result).toFixed(places + 1));
...
result = (result * offset + remainder) / offset;
```
Let me know if I your method was preferred, and revert.

**Comment by kofrasa** [comment]
I like it

**Comment by kofrasa** [comment]
> I like it. The behaviour is unspecified for how to deal with rounding the fractional part to non-whole numbers.

My changes still fails for `0.0125, 3` -> `0.012` MongoDB returns `0.013`.

**Comment by Gervwyk** [comment]
Looking into fixing this, but I cannot seem to find a pattern for what the logic is for Mognodb $round. Consider the following aggregation example and results:
```json
[{$project: {
   000: {$round: [1905,-1]},
   001: {$round: [1915,-1]},
   002: {$round: [1925,-1]},
   003: {$round: [1935,-1]},
   004: {$round: [1945,-1]},
   005: {$round: [1955,-1]},
   006: {$round: [1965,-1]},
   007: {$round: [1975,-1]},
   008: {$round: [1985,-1]},
   009: {$round: [1995,-1]},
   00: {$round: [190.5,0]},
   01: {$round: [191.5,0]},
   02: {$round: [192.5,0]},
   03: {$round: [193.5,0]},
   04: {$round: [194.5,0]},
   05: {$round: [195.5,0]},
   06: {$round: [196.5,0]},
   07: {$round: [197.5,0]},
   08: {$round: [198.5,0]},
   09: {$round: [199.5,0]},
   10: {$round: [19.05,1]},
   11: {$round: [19.15,1]},
   12: {$round: [19.25,1]},
   13: {$round: [19.35,1]},
   14: {$round: [19.45,1]},
   15: {$round: [19.55,1]},
   16: {$round: [19.65,1]},
   17: {$round: [19.75,1]},
   18: {$round: [19.85,1]},
   19: {$round: [19.95,1]},
   20: {$round: [19.005,2]},
   21: {$round: [19.015,2]},
   22: {$round: [19.025,2]},
   23: {$round: [19.035,2]},
   24: {$round: [19.045,2]},
   25: {$round: [19.055,2]},
   26: {$round: [19.065,2]},
   27: {$round: [19.075,2]},
   28: {$round: [19.085,2]},
   29: {$round: [19.095,2]},
   30: {$round: [19.0005,3]},
   31: {$round: [19.0015,3]},
   32: {$round: [19.0025,3]},
   33: {$round: [19.0035,3]},
   34: {$round: [19.0045,3]},
   35: {$round: [19.0055,3]},
   36: {$round: [19.0065,3]},
   37: {$round: [19.0075,3]},
   38: {$round: [19.0085,3]},
   39: {$round: [19.0095,3]},
   40: {$round: [19.00005,4]},
   41: {$round: [19.00015,4]},
   42: {$round: [19.00025,4]},
   43: {$round: [19.00035,4]},
   44: {$round: [19.00045,4]},
   45: {$round: [19.00055,4]},
   46: {$round: [19.00065,4]},
   47: {$round: [19.00075,4]},
   48: {$round: [19.00085,4]},
   49: {$round: [19.00095,4]},
   50: {$round: [19.000005,5]},
   51: {$round: [19.000015,5]},
   52: {$round: [19.000025,5]},
   53: {$round: [19.000035,5]},
   54: {$round: [19.000045,5]},
   55: {$round: [19.000055,5]},
   56: {$round: [19.000065,5]},
   57: {$round: [19.000075,5]},
   58: {$round: [19.000085,5]},
   59: {$round: [19.000095,5]},
}}]
```
results in:
```json
{
    "000" : 1900.0,
    "001" : 1920.0,
    "002" : 1920.0,
    "003" : 1940.0,
    "004" : 1940.0,
    "005" : 1960.0,
    "006" : 1960.0,
    "007" : 1980.0,
    "008" : 1980.0,
    "009" : 2000.0,
    "00" : 190.0,
    "01" : 192.0,
    "02" : 192.0,
    "03" : 194.0,
    "04" : 194.0,
    "05" : 196.0,
    "06" : 196.0,
    "07" : 198.0,
    "08" : 198.0,
    "09" : 200.0,
    "10" : 19.1,
    "11" : 19.1,
    "12" : 19.2,
    "13" : 19.4,
    "14" : 19.4,
    "15" : 19.6,
    "16" : 19.6,
    "17" : 19.8,
    "18" : 19.9,
    "19" : 19.9,
    "20" : 19.0,
    "21" : 19.02,
    "22" : 19.02,
    "23" : 19.04,
    "24" : 19.05,
    "25" : 19.05,
    "26" : 19.07,
    "27" : 19.07,
    "28" : 19.09,
    "29" : 19.09,
    "30" : 19.0,
    "31" : 19.002,
    "32" : 19.003,
    "33" : 19.003,
    "34" : 19.005,
    "35" : 19.006,
    "36" : 19.006,
    "37" : 19.008,
    "38" : 19.009,
    "39" : 19.009,
    "40" : 19.0001,
    "41" : 19.0002,
    "42" : 19.0003,
    "43" : 19.0004,
    "44" : 19.0005,
    "45" : 19.0006,
    "46" : 19.0007,
    "47" : 19.0008,
    "48" : 19.0008,
    "49" : 19.0009,
    "50" : 19.00001,
    "51" : 19.00002,
    "52" : 19.00003,
    "53" : 19.00004,
    "54" : 19.00005,
    "55" : 19.00005,
    "56" : 19.00006,
    "57" : 19.00007,
    "58" : 19.00008,
    "59" : 19.0001
}
```
Am I missing something or is there a bug in the behaviour for `$round` on mongodb? 
I check their Jirra issues and found nothing.

**Comment by kofrasa** [comment]
The behaviour is inconsistent. Will leave this issue open until we have more clarity.

**Comment by Gervwyk** [comment]
According to MongoDB, this is considered normal. See https://jira.mongodb.org/browse/SERVER-71557
Should we leaving it as is and just updating the tests?

**Comment by kofrasa** [comment]
Not much can be done in this case. Floating point arithmetic is all about approximations so is imprecise by definition. The rounded values will be more consistent in MongoDB using Decimal128.

**Comment by kofrasa** [comment]
I think we can close this issue.

**Pull request closed without merging**
