### PR TITLE
Add collation to aggregator config interface

### PR DESCRIPTION
**Pull request by stefanholzapfel**
Hi @kofrasa !

In the latest versions something is wrong with the options handed over to the aggregation.

It seems they are wrapped in an additional "config" property.

I recognized that because the collations I defined when creating an aggregator were no longer applied.

I did a quick fix for collations within the sort operator (because there they have impact on the result). I don't know where else it could cause problems.

In the long run, shouldn't the signature of the Aggregator be as close as possible to original Mongo's Aggregator? Mongo already provides typings for it: 
[Mongo Node Driver](https://github.com/mongodb/node-mongodb-native/blob/master/src/index.ts)

The "CollectionAggregationOptions" interface would be a perfect fit.

Thank you vor having a look!

Can you please merge the pull request in the meantime, so I don't have to bundle the fork on my own? :)

Best,
Stefan

### CODE REVIEW

**Comment by kofrasa** [comment]
Hey @stefanholzapfel, sorry about this bug. Unfortunately, the project is still missing a lot of useful tests that would have caught such regressions. It takes users who rely on the affected code paths to report the issues which obviously makes for a unpleasant experience.

I took a brief look at the Mongo Driver package. My impressions are that it doesn't quite fit what we are doing in Mingo although we do share some type interfaces. The nested `config` value that ended up in the options object in the `3.0.0` refactor was intended to separate global configuration specified at initial query creation time, from local dynamic config that is mixed in as we process objects through the pipeline. 

Different functions may have different options but I needed to preserve the global settings passed to the root query which is necessary for operators that also need to create and execute sub queries. The key is probably best named `global` instead of `config` but I digress. This is a regression and your fix is what is required. A `collation` configuration specified at the root should be passed on to all subqueries just like the `idKey`. The alternative design was to add keys for both the global and local dynamic options in a flat object, and then maintain a list of global option keys to extract and pass on where needed. I opted to compose under a single key `config` because it is easier to extract and manage.

On the PR itself I have just a couple of comments.

1. Please add `collation` as an optional argument to [Config](https://github.com/kofrasa/mingo/blob/master/src/core.ts#L21) interface.
2. It would be nice to have a test that exercises this path to avoid such regressions in the future.

Thanks for reporting this issue and I appreciate the contributions.

**Comment by stefanholzapfel** [comment]
Hi @kofrasa !

I renamed the PR, since I slightly adapted it.

I took the collation out of the specific "SortOptions" and added it to the generic config interface (like you suggested), since in Mongo you can also set in on the aggregator, independent of the operators in the pipeline. Maybe we will need it later on in different pipeline stages.

Typings are fixed, a test will follow.

**Comment by stefanholzapfel** [comment]
Hi @kofrasa !

A test for sorting with a collation as config parameter is now also included. Please merge.

Thank you!


Regards,
Stefan

**Comment by stefanholzapfel** [comment]
Hi @kofrasa !

Do you plan to push a new version to npm? Now I have to manually build and integrate to my app.

Thank you!

Cheers,
Stefan

**Comment by kofrasa** [comment]
Hi @stefanholzapfel, I will get publishing an updated version this week. Thanks

**Pull request merged**
